version = 0.1

[[task]]
name = 'build'
deps = ['src/extension.mjs']
target = 'dist/extension.js'
run = 'rollup -c'

[[task]]
name = 'build:watch'
run = 'rollup -c -w'

[[task]]
name = 'test'
deps = ['build']
run = 'code --extensionDevelopmentPath=C:\Users\Guy\Projects\jspm-vscode --extensionDevelopmentKind=web'

[[task]]
name = 'publish'
run = 'vsce publish'
