version = 0.1

[[task]]
name = 'build'
deps = ['src/extension.mjs', 'package-lock.json']
target = 'dist/extension.js'
run = 'rollup -c'

[[task]]
name = 'test'
deps = ['build']
run = 'code --extensionDevelopmentPath=$JSPM_VSCODE_PATH --extensionDevelopmentKind=web'

[[task]]
name = 'publish'
run = 'vsce publish'
